export const POST_WISH_REQUEST = "POST_WISH_REQUEST"
export const POST_WISH_SUCCESS = "POST_WISH_SUCCESS"
export const POST_WISH_FAILURE = "POST_WISH_FAILURE"

export const GET_WISH_REQUEST = "GET_WISH_REQUEST"
export const GET_WISH_SUCCESS = "GET_WISH_SUCCESS"
export const GET_WISH_FAILURE = "GET_WISH_FAILURE"

export const DELETE_WISH_REQUEST = "DELETE_WISH_REQUEST"
export const DELETE_WISH_SUCCESS = "DELETE_WISH_SUCCESS"
export const DELETE_WISH_FAILURE = "DELETE_WISH_FAILURE"

export const PATCH_WISH_REQUEST = "PATCH_WISH_REQUEST"
export const PATCH_WISH_SUCCESS = "PATCH_WISH_SUCCESS"
export const PATCH_WISH_FAILURE = "PATCH_WISH_FAILURE"
