export const POST_WISH_REQUEST = "POST_WISH_REQUEST"
export const POST_WISH_SUCCESS = "POST_WISH_SUCCESS"
export const POST_WISH_FAILURE = "POST_WISH_FAILURE"

export const GET_WISH_REQUEST = "GET_WISH_REQUEST"
export const GET_WISH_SUCCESS = "GET_WISH_SUCCESS"
export const GET_WISH_FAILURE = "GET_WISH_FAILURE"

