export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILURE = "GET_DATA_FAILURE"

export const GET_DATA_FILTER = "GET_DATA_FILTER"

export const UPDATE_FILTER_DATA = "UPDATE_FILTER_DATA"

export const SET_FILTER_DATA = "UPDATED_FILTER_DATA"


